import type { Metadata } from "next";
import "./globals.css";

// const luxeUnoNormal = localFont({
//   src: "/fonts/LuxeUno-Regular.otf",
//   variable: "--font-luxe-uno-normal",
//   weight: "400",
// })
// const luxeUnoThin = localFont({
//   src: "/fonts/LuxeUno-Thin.otf",
//   variable: "--font-luxe-uno-thin",
//   weight: "100",
// })

export const metadata: Metadata = {
  title: "Patek App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
